version: 2
updates:
  - package-ecosystem: gomod
    directory: backend/go
    schedule:
      interval: weekly
  - package-ecosystem: "npm"
    directory: frontend
    schedule:
      interval: weekly
