[package]
name = "hottocoffee"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
chrono = "0.4.26"
sqlx = { version = "0.7.1", features = ["mysql", "runtime-tokio-rustls", "chrono"] }
