[package]
name = "hottocoffee"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
axum = "0.6.18"
serde = { features = ["derive"] }
tracing-subscriber = "0.3.17"
derive-new = "0.5.9"
hmac = "0.12.1"
jsonwebtoken = "8.3.0"
chrono = "0.4.26"
