/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export type paths = Record<string, never>;

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    Batch: {
      /** Format: int64 */
      id: number;
      batch_name: string;
      server_name: string;
      /** @description ex.) 30 * * * * */
      cron_setting: string;
      /** Format: ISO 8601 */
      initial_date: string;
      /**
       * Format: int64 
       * @description Unit -> Minutes
       */
      time_limit: number;
      /**
       * Format: int64 
       * @description Unit -> Minutes
       */
      estimated_duration?: number;
    };
    BatchCreate: {
      batch_name: string;
      server_name: string;
      /** @description ex.) 30 * * * * */
      cron_setting: string;
      /** Format: ISO 8601 */
      initial_date: string;
      /**
       * Format: int64 
       * @description Unit -> Minutes
       */
      time_limit: number;
      /**
       * Format: int64 
       * @description Unit -> Minutes
       */
      estimated_duration?: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type external = Record<string, never>;

export type operations = Record<string, never>;
