openapi: 3.0.0
info:
  title: hottocoffee
  version: "0.0.1"
servers:
  - url: "http://localhost:3000"
paths:
  "/api/batch":
    description: "an endpoint for batch"
    get:
      parameters:
        - in: query
          name: keyword
          schema:
            type: string
          required: false
      summary: get batch list
      tags: [batch]
      description: get batch list. response can be filtered by keyword.
      responses:
        "200":
          description: success filter and can get batch list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "./schemas/batch.yaml#Batch"
        "400":
          description: bad request
          content:
            application/json:
              schema:
                $ref: "./schemas/error.yaml#Error"
        "500":
          description: internal server error
          content:
            application/json:
              schema:
                $ref: "./schemas/error.yaml#Error"
    post:
      tags: [batch]
      summary: register batch
      description: register new batch
      responses:
        "200":
          description: success to create
          content:
            application/json:
              schema:
                $ref: "./schemas/batch.yaml#Batch"

      requestbody:
        content:
          application/json:
            schema:
              $ref: "./schemas/batch.yaml#Batch"
  "/api/calendar":
    description: batch status for calendar
    get:
      tags:
        - calendar
      parameters:
        - in: query
          name: start_date
          schema:
            type: string
          required: false
          description: query for filtering
        - in: query
          name: end_date
          schema:
            type: string
          required: false
          description: query for filtering
      responses:
        "200":
          description: return batch history list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "./schemas/history.yaml#History"
        "500":
          description: internal server error
          content:
            application/json:
              schema:
                $ref: "./schemas/error.yaml#Error"
  "/api/batch/{id}/history":
    description: batch history
    get:
      tags:
        - batch history
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      responses:
        "200":
          description: success to get history
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "./schemas/history.yaml#History"
        "400":
          description: batch not found.
          content:
            application/json:
              schema:
                $ref: "./schemas/error.yaml#Error"
        "500":
          description: internal server error
          content:
            application/json:
              schema:
                $ref: "./schemas/error.yaml#Error"
    post:
      tags:
        - batch history
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: id of "./schemas/history.yaml#History"
      requestbody:
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  enum: [before_started, in_progress, success, failed]
      responses:
        "200":
          description: success to receive
          content:
            application/json:
              schema:
                $ref: "./schemas/success.yaml#Success"
        "500":
          description: internal server error
          content:
            application/json:
              schema:
                $ref: "./schemas/error.yaml#Error"
  "/api/batch/{id}/history/{historyId}":
    description: Get specific batch history
    get:
      tags:
        - batch history
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
        - in: path
          name: historyId
          schema:
            type: integer
          required: true
      responses:
        "200":
          description: Success to get history
          content:
            application/json:
              schema:
                $ref: "./schemas/history.yaml#History"
        "400":
          description: Batch not found.
          content:
            application/json:
              schema:
                $ref: "./schemas/error.yaml#Error"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "./schemas/error.yaml#Error"
components:
  schemas:
    batch:
      $ref: "./schemas/batch.yaml#Batch"
