name: Backend build check

on:
  pull_request:
    paths:
      - 'backend/go/**'
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: ./backend/go

jobs:
  check-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: ./backend/go/go.mod
          cache-dependency-path: ./backend/go/go.sum
      - name: Check format
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: test -z $(gofmt -l .)
      - name: Test and collect coverage
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: go test ./... -short -race -covermode=atomic -coverprofile=coverage.txt
      - name: Test
        if: ${{ matrix.os != 'ubuntu-latest' }}
        run: go test ./... -short -race
      - name: Build
        run: go build
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        if: ${{ matrix.os == 'ubuntu-latest' }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
