name: "swagger release"

on:
  pull_request:
    branches:
      - 'main'
    types: [opened, synchronize, closed]

jobs:
  swagger-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install swagger-cli
        run: |
          npm install -g swagger-cli

      - name: Validate swagger files
        run: |
          swagger-cli validate -d swagger.yaml --type yaml --format 3

  swagger-release:
    if: github.event.pull_request.merged == true
    needs: swagger-validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install swagger-cli
        run: |
          npm install -g swagger-cli

      - name: Inject Swagger static files
        run: |
          wget https://github.com/swagger-api/swagger-ui/archive/refs/tags/v4.1.0.tar.gz
          tar -zxvf v4.1.0.tar.gz swagger-ui-4.1.0/dist/
          cp swagger-ui-4.1.0/dist/* docs/

      - name: Combine Multiple Swagger Files
        run: |
          swagger-cli bundle main.yaml --outfile docs/swagger.yaml --type yaml --format 3

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
